name: Explorations In Story Telling
favicon: null
layout_spectrum: 0.02726
typography_spectrum: 0.51868
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.375
  lightness: 0.25
  saturation: 0.8125
  rhythmicContrast: 0.5812628152780235
purpose: []
